/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Unidad3;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


public class Main extends javax.swing.JFrame {
    Driver funcion = new Driver();
    String rutaArchivo = "";
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        contenedorBotones = new javax.swing.JToolBar();
        btnNuevo = new javax.swing.JButton();
        btnAbrir = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        btnVerificar = new javax.swing.JButton();
        btnEjecutar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtSalida = new javax.swing.JTextArea();
        jMenuBar2 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        clicNuevo = new javax.swing.JMenuItem();
        clicAbrir = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        clicGuardar = new javax.swing.JMenuItem();
        clicGuardarComo = new javax.swing.JMenuItem();
        clicCerrar = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        clicSalir = new javax.swing.JMenuItem();
        menuEditar = new javax.swing.JMenu();
        clicDeshacer = new javax.swing.JMenuItem();
        clicRehacer = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        clicCopiar = new javax.swing.JMenuItem();
        clicCortar = new javax.swing.JMenuItem();
        clicPegar = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        clicSeleccionarTodo = new javax.swing.JMenuItem();
        clicBuscar = new javax.swing.JMenuItem();
        menuCompilar = new javax.swing.JMenu();
        clicVerificar = new javax.swing.JMenuItem();
        clicEjecutar = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        clicASCII = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Compilador");
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(600, 30));

        contenedorBotones.setRollover(true);
        contenedorBotones.setPreferredSize(new java.awt.Dimension(600, 25));

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/file.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setFocusable(false);
        btnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clicNuevo(evt);
            }
        });
        contenedorBotones.add(btnNuevo);

        btnAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/folder.png"))); // NOI18N
        btnAbrir.setText("Abrir");
        btnAbrir.setFocusable(false);
        btnAbrir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAbrir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clicAbrir(evt);
            }
        });
        contenedorBotones.add(btnAbrir);

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setToolTipText("");
        btnGuardar.setEnabled(false);
        btnGuardar.setFocusable(false);
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clicGuardar(evt);
            }
        });
        contenedorBotones.add(btnGuardar);
        contenedorBotones.add(jSeparator5);

        btnVerificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/like.png"))); // NOI18N
        btnVerificar.setText("Verificar");
        btnVerificar.setFocusable(false);
        btnVerificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVerificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clicVerificar(evt);
            }
        });
        contenedorBotones.add(btnVerificar);

        btnEjecutar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/play-button.png"))); // NOI18N
        btnEjecutar.setText("Ejecutar");
        btnEjecutar.setFocusable(false);
        btnEjecutar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEjecutar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clicEjecutar(evt);
            }
        });
        contenedorBotones.add(btnEjecutar);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedorBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedorBotones, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
        );

        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setPreferredSize(new java.awt.Dimension(599, 200));

        jEditorPane1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(jEditorPane1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 599, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
        );

        jPanel3.setPreferredSize(new java.awt.Dimension(600, 30));

        jLabel1.setText("Resultado:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel4.setPreferredSize(new java.awt.Dimension(600, 80));

        txtSalida.setEditable(false);
        txtSalida.setBackground(new java.awt.Color(0, 0, 0));
        txtSalida.setColumns(20);
        txtSalida.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtSalida.setForeground(new java.awt.Color(255, 255, 255));
        txtSalida.setRows(5);
        jScrollPane2.setViewportView(txtSalida);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 79, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
        );

        menuArchivo.setMnemonic('A');
        menuArchivo.setText("Archivo");

        clicNuevo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        clicNuevo.setMnemonic('n');
        clicNuevo.setText("Nuevo");
        clicNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clicNuevo(evt);
            }
        });
        menuArchivo.add(clicNuevo);

        clicAbrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        clicAbrir.setMnemonic('a');
        clicAbrir.setText("Abrir");
        clicAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clicAbrir(evt);
            }
        });
        menuArchivo.add(clicAbrir);
        menuArchivo.add(jSeparator1);

        clicGuardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        clicGuardar.setMnemonic('s');
        clicGuardar.setText("Guardar");
        clicGuardar.setEnabled(false);
        clicGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clicGuardar(evt);
            }
        });
        menuArchivo.add(clicGuardar);

        clicGuardarComo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        clicGuardarComo.setMnemonic('g');
        clicGuardarComo.setText("Guardar como...");
        clicGuardarComo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clicGuardarComo(evt);
            }
        });
        menuArchivo.add(clicGuardarComo);

        clicCerrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        clicCerrar.setMnemonic('w');
        clicCerrar.setText("Cerrar");
        clicCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clicCerrarActionPerformed(evt);
            }
        });
        menuArchivo.add(clicCerrar);
        menuArchivo.add(jSeparator2);

        clicSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        clicSalir.setText("Salir");
        clicSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clicSalirActionPerformed(evt);
            }
        });
        menuArchivo.add(clicSalir);

        jMenuBar2.add(menuArchivo);

        menuEditar.setMnemonic('E');
        menuEditar.setText("Editar");

        clicDeshacer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        clicDeshacer.setMnemonic('z');
        clicDeshacer.setText("Deshacer");
        menuEditar.add(clicDeshacer);

        clicRehacer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_MASK));
        clicRehacer.setMnemonic('y');
        clicRehacer.setText("Rehacer");
        clicRehacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clicRehacerActionPerformed(evt);
            }
        });
        menuEditar.add(clicRehacer);
        menuEditar.add(jSeparator3);

        clicCopiar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        clicCopiar.setMnemonic('c');
        clicCopiar.setText("Copiar");
        menuEditar.add(clicCopiar);

        clicCortar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        clicCortar.setMnemonic('x');
        clicCortar.setText("Cortar");
        clicCortar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clicCortarActionPerformed(evt);
            }
        });
        menuEditar.add(clicCortar);

        clicPegar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        clicPegar.setMnemonic('v');
        clicPegar.setText("Pegar");
        menuEditar.add(clicPegar);
        menuEditar.add(jSeparator4);

        clicSeleccionarTodo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        clicSeleccionarTodo.setMnemonic('a');
        clicSeleccionarTodo.setText("Seleccionar todo");
        menuEditar.add(clicSeleccionarTodo);

        clicBuscar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        clicBuscar.setMnemonic('f');
        clicBuscar.setText("Buscar");
        menuEditar.add(clicBuscar);

        jMenuBar2.add(menuEditar);

        menuCompilar.setMnemonic('C');
        menuCompilar.setText("Compilar");

        clicVerificar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        clicVerificar.setMnemonic('v');
        clicVerificar.setText("Verificar");
        clicVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clicVerificar(evt);
            }
        });
        menuCompilar.add(clicVerificar);

        clicEjecutar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        clicEjecutar.setMnemonic('e');
        clicEjecutar.setText("Ejecutar");
        clicEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clicEjecutar(evt);
            }
        });
        menuCompilar.add(clicEjecutar);

        jMenuBar2.add(menuCompilar);

        menuAyuda.setMnemonic('H');
        menuAyuda.setText("Ayuda");

        clicASCII.setText("ASCII");
        clicASCII.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clicascii(evt);
            }
        });
        menuAyuda.add(clicASCII);

        jMenuBar2.add(menuAyuda);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(616, 438));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void clicGuardarComo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clicGuardarComo
        JFileChooser fc = new JFileChooser(".");
        int opcion = fc.showSaveDialog(this);        
        if(opcion == JFileChooser.APPROVE_OPTION )
        {
            clicGuardar.setEnabled(true);
            btnGuardar.setEnabled(true);
            try {
                rutaArchivo = funcion.guardarComo(fc.getSelectedFile(), jEditorPane1.getText());
            } catch (IOException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
        }    
        
        
    }//GEN-LAST:event_clicGuardarComo

    private void clicRehacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clicRehacerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clicRehacerActionPerformed

    private void clicCortarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clicCortarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clicCortarActionPerformed

    private void clicascii(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clicascii
        txtSalida.setText(funcion.Ascii());
        
    }//GEN-LAST:event_clicascii

    private void clicAbrir(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clicAbrir
        jEditorPane1.setText(funcion.abrir(getRuta()));
    }//GEN-LAST:event_clicAbrir

    private void clicCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clicCerrarActionPerformed
        
        //Si = 0
        //No = 1
        //Cancelar = 2
        JOptionPane.showMessageDialog(null, funcion.rutaArchivo);
        if(!"".equals(rutaArchivo))
        {
            
            int respuesta = JOptionPane.showConfirmDialog(null, "¿Desea guardar antes de cerrar?");
            if(respuesta==0)
            {
                try {
                    funcion.guardar(jEditorPane1.getText(), 0);
                    } catch (FileNotFoundException ex) {
                        Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                    }
                jEditorPane1.setText("");
            }
            else if(respuesta == 1)
                jEditorPane1.setText("");
            clicGuardar.setEnabled(false);
            btnGuardar.setEnabled(false);
            
        }
    }//GEN-LAST:event_clicCerrarActionPerformed

    private void clicGuardar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clicGuardar
        try 
        {
            funcion.guardar(jEditorPane1.getText(), 0);
        } catch (FileNotFoundException ex) 
        {
            JOptionPane.showMessageDialog(null, ex);
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_clicGuardar

    private void clicSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clicSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_clicSalirActionPerformed

    private void clicVerificar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clicVerificar
        JOptionPane.showMessageDialog(null, "Has ingresado a estsasasase botón");
        try 
        {
            funcion.guardar(jEditorPane1.getText(), 1);
            txtSalida.setText(funcion.verificar());
            
        } catch (FileNotFoundException ex) 
        {
            JOptionPane.showMessageDialog(null, ex);
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_clicVerificar

    private void clicEjecutar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clicEjecutar
        // TODO add your handling code here:
        //Hola
    }//GEN-LAST:event_clicEjecutar

    private void clicNuevo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clicNuevo
        // TODO add your handling code here:
        //Hola
    }//GEN-LAST:event_clicNuevo
    
    private String getRuta()
    {
        String ruta="";
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.dir")));
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            ruta = fileChooser.getSelectedFile().getAbsolutePath();
        }
        return ruta;
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnEjecutar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnVerificar;
    private javax.swing.JMenuItem clicASCII;
    private javax.swing.JMenuItem clicAbrir;
    private javax.swing.JMenuItem clicBuscar;
    private javax.swing.JMenuItem clicCerrar;
    private javax.swing.JMenuItem clicCopiar;
    private javax.swing.JMenuItem clicCortar;
    private javax.swing.JMenuItem clicDeshacer;
    private javax.swing.JMenuItem clicEjecutar;
    private javax.swing.JMenuItem clicGuardar;
    private javax.swing.JMenuItem clicGuardarComo;
    private javax.swing.JMenuItem clicNuevo;
    private javax.swing.JMenuItem clicPegar;
    private javax.swing.JMenuItem clicRehacer;
    private javax.swing.JMenuItem clicSalir;
    private javax.swing.JMenuItem clicSeleccionarTodo;
    private javax.swing.JMenuItem clicVerificar;
    private javax.swing.JToolBar contenedorBotones;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenu menuCompilar;
    private javax.swing.JMenu menuEditar;
    private javax.swing.JTextArea txtSalida;
    // End of variables declaration//GEN-END:variables
}
